name: publish
on: [push]
jobs:
 publish-hello-docker-image:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: reenalmainly
         password: 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 
     - name: Build the hello-docker Docker image
       run: |
         docker build . --tag ghcr.io/reenalmainly/hello-docker-gcr-demo:latest
         docker run ghcr.io/reenalmainly/hello-docker-gcr-demo:latest
         docker push ghcr.io/reenalmainly/hello-docker-gcr-demo:latest
       
