name: publish
on: [push]
jobs:
 publish-hello-docker-image:
   runs-on: ubuntu-latest
   steps:
     -
       name: Build the hello-docker Docker image
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     #run: |
         #echo $CR_PAT | docker login ghcr.io -u reenalmainly --password-stdin
     #env: 
         #CR_PAT : ${{secrets.CR_PAT}}       
