name: publish
on: [push]
jobs:
 publish-hello-docker-image:
   runs-on: ubuntu-latest
   steps:
     -
       name: Build the hello-docker Docker image
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
         run: |
                 docker build . --tag ghcr.io/reenalmainly/hello-docker-gcr-demo:latest
                 docker run ghcr.io/reenalmainly/hello-docker-gcr-demo:latest
                 docker push ghcr.io/reenalmainly/hello-docker-gcr-demo:latest
     #env: 
         #CR_PAT : ${{secrets.CR_PAT}}       
